### ISSUE TITLE
direct link to contact us is not showing on mobile 

### ISSUE THREAD

**Issue by jalbertsr** [kiwicom/smart-faq#398] opened 2018-06-11 12:49 UTC
direct link to contact us is not showing on mobile  in the articles compared to how it should show on desktop

https://monosnap.com/file/EDrvCLtR5gYCHOph6Qy74fMNMfUjE0

**Comment by kantord** [comment] 2018-06-11 14:53
Probably solved by https://github.com/kiwicom/smart-faq/pull/404

**Comment by kantord** [comment] 2018-06-11 14:54
Possibly duplicate of #402

**Comment by jaroslav-kubicek** [comment] 2018-06-19 08:01
so I guess it can be closed, right? 🙂

**Comment by kantord** [comment] 2018-06-21 13:37
![2018-06-21-153512_1025x1546_scrot](https://user-images.githubusercontent.com/3704904/41722458-ed372c3c-7568-11e8-81b6-41df0c3b6daf.png)
Will be fixed by https://github.com/kiwicom/smart-faq/pull/466

**Closed** 2018-06-21 13:41 UTC
Labels: Responsive design, bug
