### ISSUE TITLE
Long Accordion overflows parent container

### ISSUE THREAD

**Issue by git-toni** [kiwicom/smart-faq#188] opened 2018-05-17 08:11 UTC
According to [design](https://app.zeplin.io/project/5a8e8992554d385c76ad5aeb/screen/5aeb0daac11774fb37dd05eb) there shouldn't be scroll but the screen should be "cut" instead. 

However in some cases (like the one below) the flight has so many legs even that single flight doesn't fit in the screen. Should we then add scrolls somewhere? @mjancik @MRTNKCR 

![image](https://user-images.githubusercontent.com/2466887/40164530-1b91258a-59ba-11e8-8b9a-a590173ea96b.png)

**Comment by mjancik** [comment] 2018-05-17 08:16
Yes. There should be a scroll, so the user can see all the information.

**Comment by jaroslav-kubicek** [comment] 2018-05-17 11:55
Duplicate of #185, I will close #185 then

**Closed** 2018-05-18 09:32 UTC
Labels: bug

**Comment by MagdalenaAlmanova** [comment] 2018-05-29 19:41
I cannot try this, because test login has only one direct flight. Have you any idea how can I test it, please? 
Thank you very much :)

**Comment by MagdalenaAlmanova** [comment] 2018-05-30 18:45
I think that is ok :)
