### ISSUE TITLE
Handle 404 not found for subcategory

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#590] opened 2018-07-30 09:04 UTC
Handle when the subcategory is not found (url is like `/faq/someSubcategoryIdBlaBla`)

<img width="659" alt="screen shot 2018-07-30 at 11 00 58" src="https://user-images.githubusercontent.com/2174629/43387987-3b34c186-93e8-11e8-819a-a9f33d081640.png">

**Comment by kantord** [comment] 2018-07-31 16:47
@jaroslav-kubicek how can this be reproduced?
@mjancik what should this look like?

**Comment by jalbertsr** [comment] 2018-08-02 09:49
I also can't reproduce it.

**Comment by jaroslav-kubicek** [comment] 2018-08-03 08:16
Can't reproduce? Guys, have you ever tried? it's in the description, just specify invalid categoryId and that's it: https://kiwicom.github.io/smart-faq/?help=%2Ffaq%2FRkFRQ2F0ZWsdscnk6ODk%3D

**Comment by kantord** [comment] 2018-08-03 09:41
Well use the same error design as for the bookings, but with different text.

**Comment by jalbertsr** [comment] 2018-08-03 20:18
closed by #616

**Closed by jalbertsr** 2018-08-03 20:18 UTC
Labels: bug
