### ISSUE TITLE
Display detail of the static FAQ

### ISSUE THREAD

**Issue by jaroslav-kubicek** [kiwicom/smart-faq#30] opened 2018-03-21 12:25 UTC
Acceptance criteria:
- display specific FAQ page according to designs
- "was this article helpful" won't be implemented as part of this
- "contact page" not part of this

<img width="383" alt="screen shot 2018-03-21 at 12 22 08" src="https://user-images.githubusercontent.com/2174629/37709694-eb7aaf8a-2d02-11e8-8759-b728adfb7474.png">

https://marvelapp.com/7iihb90/screen/39265579

**Comment by MagdalenaAlmanova** [comment] 2018-04-18 20:30
I saw a few mistakes. First, I think instead of the button **_"Back"_** should be the button **_"Search"_** according to Zeplin. 
**Demo v.**
![screen shot 2018-04-18 at 22 22 29](https://user-images.githubusercontent.com/37298895/38956133-06d349d0-4357-11e8-9d6c-3c371b28506a.png)

**Prototype v.**
![screen shot 2018-04-18 at 21 48 16](https://user-images.githubusercontent.com/37298895/38955299-8503da48-4354-11e8-8982-87e987aef16d.png)

Secondly, if I scrolled down, the text was outside of the box on the bottom.

**Demo v.**
![screen shot 2018-04-18 at 22 06 23](https://user-images.githubusercontent.com/37298895/38955376-ca16ebca-4354-11e8-9905-390613256ce0.png)

Another, there was missing **_"track"_**, for the better understanding look at the screenshot.
**_Demo v._**
![screen shot 2018-04-18 at 22 09 24](https://user-images.githubusercontent.com/37298895/38955520-3d34a23c-4355-11e8-9166-f99e8801bf30.png)
Prototy v.
![screen shot 2018-04-18 at 22 09 38](https://user-images.githubusercontent.com/37298895/38955535-43059e50-4355-11e8-9e8a-3d1107c74d87.png)

The last mistake, in the **_Chrome and Opera_** both last versions, the bold font was not shown. See on the screenshot.
![screen shot 2018-04-18 at 22 16 48](https://user-images.githubusercontent.com/37298895/38955893-35e9aa76-4356-11e8-9ee4-022f9b00dadd.png)

For future, please let me know where I will do testing. (https://kiwicom.github.io/smart-faq/ or https://introduce-smart-faq.fe.staging.kiwi.com/en/).

Thank you,
Meggy

**Comment by kantord** [comment] 2018-04-30 13:32
Regarding the `&nbsp;` thing:
I think think the issue is with the data returned by the API. Here's the JSON returned, which corresponds to the issue in the screenshot.

``
{
  "data": {
    "FAQArticle": {
      "content": "<div>There may be a delay due to minor technical issues. We will send you confirmation as soon as the booking has been completed.&nbsp;<br><br>If, after an extended wait, you still haven't received an email from us, please contact our Customer Support Team to ensure that we have the correct email address.<\/div>",
      "id": "RkFRQXJ0aWNsZTozMg==",
      "perex": "If you think your e-ticket might be delayed, hang tight. We've begun processing your booking.",
      "title": "Delayed e-ticket"
    }
  }
}
``

No wonder we see `&nbsp;`, as it is included in the actual text of the article. As you can see, the document is wrapped in HTML tags (`<div>`) and contains `&nbsp;<br><br>`. In this repo, however, this field is assumed to be in Markdown format (see FAQArticleDetailContent.js).

Here are the possible solutions I can think of:
- Fix the content returned by the API, so that it returns valid Markdown, and without meaningless HTML tags and &nbsp;
- Assume the field to contain raw HTML instead of Markdown (in FAQArticleDetailContent.js)
- Technically possible but very ugly and hackish solution: find and remove any occurrence of `&nbsp;` on the frontend or in the graphql proxy 

I think the first option is really the best solution, as I don't see any reason to use HTML in that field and I definitely don't see a reason to use `&nbsp;<br><br>`.

**Comment by kantord** [comment] 2018-04-30 13:44
![2018-04-30-154051_1056x1231_scrot](https://user-images.githubusercontent.com/3704904/39430065-0b825aea-4c8d-11e8-8e35-9686cd5c4f65.png)

This is Chromium (Chrome),, version 66. Arch Linux.

On which operating system and Chrome version did the bold font issue happen? Is the issue persistent?

**Comment by MagdalenaAlmanova** [comment] 2018-05-01 19:09
No, The mistake is not persistent. But a new mistake is here.  Look at the screenshot. 
![screen shot 2018-05-01 at 21 04 13](https://user-images.githubusercontent.com/37298895/39488855-e598ff3a-4d83-11e8-9ed2-ed8c0284de77.png)

Meggy

**Comment by kantord** [comment] 2018-05-07 08:13
Everything here is fixed now, correct?

**Comment by jaroslav-kubicek** [comment] 2018-05-09 10:40
Can we close this? 🙂  cc @kantord  and @MagdalenaAlmanova

**Comment by kantord** [comment] 2018-05-09 11:31
I think we can

**Comment by MagdalenaAlmanova** [comment] 2018-05-09 11:51
Yes, we can :)

**Closed by MagdalenaAlmanova** 2018-05-09 11:51 UTC
Labels: User story
